### ISSUE TITLE
Restore old tape recordings

### ISSUE THREAD

**Issue by hobodrifterdavid** [slp-rl/aero#1]
Hello,
I wondered if you might have a comment on how to improve the clarity of recordings such as these:
https://fsi-languages.yojik.eu/languages/FSI/fsi-french-basic.html

They are from old (reel-to-reel) tapes, with some kind of NR/noise gate, and low-bitrate compression.

Maybe I could make a dataset of original and (simulated) degraded recordings by running clean recordings through this cassette-tape simulator VST plugin?

https://www.wavesfactory.com/audio-plugins/cassette/
https://github.com/teragonaudio/MrsWatson

Thanks for your time.

**Comment by m-mandel** [comment]
Hi,
You can try to train the model on datasets with similar noise.
Alternatively, you can try to run the [predict pipeline](https://github.com/slp-rl/aero#predict-on-single-sample) as is, but this may not work as AERO is not robust to audio from different sources.
