### ISSUE TITLE
BEHMGAN Training parameters

### ISSUE THREAD

**Issue by abreuwallace** [slp-rl/aero#12]
Hi,
As you've done in your paper, I'm also trying to train BEHMGAN with 44.1 kHz recordings but I'm having issues -- the frequencies generated above 4kHz are shifted some miliseconds in time. 

Did you have this kind of issue at some point in training? If no, could you share the parameters of the conf file used for this setting?

Thanks

Wallace

**Comment by m-mandel** [comment]
Hey Wallace,

I did not encounter such an issue. 
I don't have a conf file at the moment, if I find one in the next week - I'll send it over.

Best
M
