### ISSUE TITLE
How to use this to improve audio quality of existing recordings?

### ISSUE THREAD

**Issue by FurkanGozukara** [slp-rl/aero#2]
Hello.

I want to improve audio of my recordings

I didn't understand from readme that how can I achieve this

here my video that I want to improve. so what do I need to do? I am not interested in training

https://youtu.be/2zY1dQDGl3o

**Comment by m-mandel** [comment]
Hi, 
You can try to run the audio channel through the [predict pipeline](https://github.com/slp-rl/aero#predict-on-single-sample), though there is a good chance that this might not work as AERO may not be robust to audio from a variety of sources.

**Comment by FurkanGozukara** [comment]
> Hi, You can try to run the audio channel through the [predict pipeline](https://github.com/slp-rl/aero#predict-on-single-sample), though there is a good chance that this might not work as AERO may not be robust to audio from a variety of sources.

ty for quick reply
which checkpoint should i use for this task?

![image](https://user-images.githubusercontent.com/19240467/217796924-c745a24a-8f54-4714-8f69-b8fa7e12c31f.png)

**Comment by m-mandel** [comment]
It depends what sampling rate is the audio in your video.
From what I hear, I'm not sure there is much to improve upon.
